spring:
  application:
    name: ms-order
    
  jpa:
    generate-ddl: true
    defer-datasource-initialization: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    
  datasource:
    driverClassName: org.postgresql.Driver
    password: challenge
    username: ambev
    url: jdbc:postgresql://host.docker.internal:5432/ordersdb
    hikari: 
      maximum-pool-size: 20
  profiles:
    active: local
  
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 60000

management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'


springdoc:
  api-docs:
    version: OPENAPI_3_1


api:
  documentation:
    title: API Order Challenger
    description: API Order Challenger project for Ambev's technical recruitment process
    version: 1.0
    team: 
      name: Ambev
      url: https://www.ambev.com.br/
      email: email@ambev.com.br


      
server:
  servlet:
    context-path: /v1/api
  port: '8080'
  
  
logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG
  pattern:
    console: "%clr(TS=){faint}%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z', UTC}){faint}
      [%t] %clr(LEVEL=){faint}%clr(${LOG_LEVEL_PATTERN:%p})
      %clr(TRACEID=){faint}%clr(%X{traceId:-null}){reverse} |
      %clr(CLASS=){faint}%clr(%logger{26}){cyan} |
      %m%n%ex"
